#! /bin/bash
# cor
b="\033[1;37m"
v="\033[1;33m"
m="\033[1;32m"
n="\033[1;31m"
s="\033[1;35m"
O="\033[1;36m"
f="\033[0m"
barra="echo -e \033[0;34m∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞=∞\033[0m"
clear
$barra
echo -e "$v EJERCICIOS DE COMANDOS EN BASH"
$barra
echo -e "$v[ $b 0 $v ]$n ° $s [VOLVER/SALIR]"
echo -e "$v[ $b 1 $v ]$n ° $m COMANDOS"
echo -e "$v[ $b 2 $v ]$n ° $m CALCULADORA"
echo -e "$v[ $b 3 $v ]$n ° $m INSTALAR DEPENDENCIAS"
echo -e "$v[ $b 4 $v ]$n ° $m REGISTRO "
echo -e "$v[ $b 5 $v ]$n ° $m VER FECHA Y HORA "
echo -e "$v[ $b 6 $v ]$n ° $m PRESIONE UNA TECLA"
echo -e "$v[ $b 7 $v ]$n ° $m ACCTUALIZAR"
$barra $O
read -p "Introduce una opcion:" opcion
case $opcion in
0) exit  ;;
1) source comandos  ;;
2) source calculadora ;;
3) source dependencias  ;;
4) source logeo ;;
5) source fecha ;;
6) source verifica-tecla ;;
7) cd && rm -irf barba-bash
git clone https://github.com/barba99/barba-bash.git
cd barba-bash && chmod +x * && bash menu ;;
*)echo -e  "$n OPCION NO VALIDA $f"
sleep 4
source menu
esac

